/** Human-readable explanations built from computed numbers (never canned claims). */
import { FUELS, fuelIntensity, priceUsdPerGJ } from './fuels'
import type { Corridor, Evaluation, Mission, Solution, Vessel } from './types'

export interface NarrativeContext {
  baseline: Evaluation
  classical: Evaluation
  corridors: Record<string, Corridor>
  vessels: Record<string, Vessel>
  mission: Mission
  accounting: 'WtW' | 'TtW'
}

const pct = (a: number, b: number) => ((a - b) / Math.max(1e-9, b)) * 100
const sgn = (x: number, d = 1) => `${x >= 0 ? '+' : '−'}${Math.abs(x).toFixed(d)}`

export function whySelected(s: Solution, ctx: NarrativeContext): string[] {
  const out: string[] = []
  const v = ctx.vessels[s.decision.vesselId]
  const c = ctx.corridors[s.decision.corridorId]
  const f = FUELS[s.decision.fuelId]
  const b = ctx.baseline
  const label = s.labels[0] ?? 'Archive'
  const dFuel = pct(s.totals.fuelT, b.totals.fuelT)
  const dCo2 = pct(s.objectives[2], b.objectives[2])
  const dCost = pct(s.totals.costUsd, b.totals.costUsd)
  const dTime = s.totals.timeH - b.totals.timeH

  out.push(
    `${label}: against the baseline (shortest corridor at design speed, ${FUELS[b.decision.fuelId].short}), this plan changes fuel ${sgn(dFuel)}%, ${ctx.accounting} CO₂e ${sgn(dCo2)}%, cost ${sgn(dCost)}% and voyage time ${sgn(dTime, 1)} h.`,
  )
  const speeds = s.decision.legSpeedsKn
  const minS = Math.min(...speeds)
  const maxS = Math.max(...speeds)
  const slowBin = speeds.indexOf(minS)
  const fastBin = speeds.indexOf(maxS)
  out.push(
    `Speed profile ${minS.toFixed(1)} to ${maxS.toFixed(1)} kn (average SOG ${s.totals.avgSpeedKn.toFixed(1)} kn): slowest in distance bin ${slowBin + 1}/${speeds.length}, fastest in bin ${fastBin + 1}. Propulsion power follows P ∝ V^${v.powerExponent}, so the engine trims speed where weather residuals are largest and recovers time where the current assists.`,
  )
  const assist = s.segments.reduce((a, x) => a + x.currentAssistKn * x.distNm, 0) / Math.max(1, s.totals.distanceNm)
  const worst = s.segments.reduce((m, x) => (x.hsM > m.hsM ? x : m), s.segments[0])
  out.push(
    `${c.name} (${Math.round(c.distanceNm)} nm, ${c.kind}): ${c.description} Distance-weighted current ${sgn(assist, 2)} kn; worst sea state Hs ${worst.hsM.toFixed(1)} m at t+${worst.tStartH.toFixed(0)} h (${worst.windKn.toFixed(0)} kn wind, ${Math.round(worst.weatherFrac * 100)}% added power).`,
  )
  out.push(
    `${f.name}: ${priceUsdPerGJ(f).toFixed(2)} $/GJ delivered at ${f.lhvMJkg} MJ/kg, lifecycle intensity ${fuelIntensity(f, 'WtW').toFixed(1)} gCO₂e/MJ (WtT ${f.wttGco2eMJ} + TtW ${f.ttwGco2eMJ}). ${f.notes}`,
  )
  if (s.decision.shorePower && s.totals.shorePowerKwh > 0) {
    out.push(`Shore power at berth: ${Math.round(s.totals.shorePowerKwh).toLocaleString()} kWh from the grid replaces auxiliary MGO; port-phase CO₂ ${s.totals.portCo2T.toFixed(1)} t versus ${(b.totals.portCo2T).toFixed(1)} t on auxiliaries in the baseline.`)
  } else {
    out.push(`Auxiliaries run at berth (${s.totals.portCo2T.toFixed(1)} t CO₂ in port); shore power was ${s.decision.shorePower ? 'requested but unavailable' : 'not selected: the cost penalty outweighed the emissions benefit under the current weights'}.`)
  }
  if (s.cvar) {
    out.push(`Uncertainty: CVaR${Math.round(s.cvar.alpha * 100)} of the risk index over ${s.cvar.scenarios} weather members is ${s.cvar.riskCvar.toFixed(2)} (mean ${s.cvar.riskMean.toFixed(2)}); fuel tail ${s.cvar.fuelCvar.toFixed(0)} t versus mean ${s.cvar.fuelMean.toFixed(0)} t.`)
  }
  if (s.warnings.length) out.push(`Conditions: ${s.warnings.join('; ')}.`)
  const slackH = (Date.parse(ctx.mission.arrivalLatest) - Date.parse(s.totals.arrivalIso)) / 3600e3
  out.push(`ETA ${s.totals.arrivalIso.slice(0, 16).replace('T', ' ')}Z leaves ${slackH.toFixed(1)} h before the latest-arrival constraint; sailing draught ${s.totals.sailingDraftM.toFixed(2)} m.`)
  return out
}

export interface ReplanExplanationInput {
  tH: number
  forecastLabel: string
  ifContinued: Evaluation
  newPlan: Evaluation
  oldCorridor: Corridor
  newCorridor: Corridor
  alpha: number
}

export function explainReplan(i: ReplanExplanationInput): string[] {
  const out: string[] = []
  const worstOld = i.ifContinued.segments.reduce((m, x) => (x.hsM > m.hsM ? x : m), i.ifContinued.segments[0])
  const worstNew = i.newPlan.segments.reduce((m, x) => (x.hsM > m.hsM ? x : m), i.newPlan.segments[0])
  out.push(`${i.forecastLabel}. Re-optimised from the live position at t+${i.tH.toFixed(0)} h with vessel and fuel fixed; corridors regenerated by A* against the updated forecast.`)
  if (i.ifContinued.violations.length) {
    out.push(`Continuing on the ${i.oldCorridor.name.toLowerCase()} would breach limits: ${i.ifContinued.violations.slice(0, 2).join('; ')}${i.ifContinued.violations.length > 2 ? ` (+${i.ifContinued.violations.length - 2} more)` : ''}.`)
  } else {
    out.push(`Continuing on the ${i.oldCorridor.name.toLowerCase()} stays within limits but meets Hs ${worstOld.hsM.toFixed(1)} m at t+${worstOld.tStartH.toFixed(0)} h with a risk index of ${i.ifContinued.totals.riskMax.toFixed(2)}.`)
  }
  const dDist = i.newPlan.totals.distanceNm - i.ifContinued.totals.distanceNm
  const dTime = i.newPlan.totals.timeH - i.ifContinued.totals.timeH
  const dFuel = i.newPlan.totals.fuelT - i.ifContinued.totals.fuelT
  out.push(
    `New plan: re-generated ${i.newCorridor.name.toLowerCase()} from the live position. Remaining distance ${sgn(dDist, 0)} nm, time ${sgn(dTime, 1)} h, fuel ${sgn(dFuel, 1)} t (${sgn(pct(i.newPlan.totals.fuelT, i.ifContinued.totals.fuelT))}%). Worst sea state now Hs ${worstNew.hsM.toFixed(1)} m; peak risk ${i.ifContinued.totals.riskMax.toFixed(2)} to ${i.newPlan.totals.riskMax.toFixed(2)}.`,
  )
  const sp = i.newPlan.decision.legSpeedsKn
  out.push(`Speed profile re-shaped to ${Math.min(...sp).toFixed(1)} to ${Math.max(...sp).toFixed(1)} kn; ETA ${i.newPlan.totals.arrivalIso.slice(0, 16).replace('T', ' ')}Z${i.newPlan.violations.length ? '. WARNING: ' + i.newPlan.violations[0] : ' within the arrival window'}.`)
  return out
}

export function solutionTitle(s: Solution): string {
  return s.labels.length ? s.labels.join(', ') : `Archive ${s.id}`
}

/** One sentence of rationale for the inspector's default state. */
export function oneLine(s: Solution, ctx: NarrativeContext): string {
  const b = ctx.baseline
  const c = ctx.corridors[s.decision.corridorId]
  const dFuel = pct(s.totals.fuelT, b.totals.fuelT)
  const dCo2 = pct(s.objectives[2], b.objectives[2])
  const dCost = pct(s.totals.costUsd, b.totals.costUsd)
  const speeds = s.decision.legSpeedsKn
  const f = FUELS[s.decision.fuelId]
  return `${sgn(dFuel)}% fuel and ${sgn(dCo2)}% ${ctx.accounting} CO₂e against the baseline for ${sgn(dCost)}% cost, on the ${c?.name.toLowerCase() ?? 'selected corridor'} at ${Math.min(...speeds).toFixed(1)} to ${Math.max(...speeds).toFixed(1)} kn burning ${f.short}${s.decision.shorePower && s.totals.shorePowerKwh > 0 ? ' with shore power at berth' : ''}.`
}
